name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  Publish:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install deps
        run: |
          sudo apt install gcc-aarch64-linux-gnu

      - name: Make
        run: |
          make clean
          make
        working-directory: impl/C

      - name: Package Binaries
        run: |
          rm impl/C/build/*.o
          tar -czvf bin.tar.gz impl/C/build/*

      - name: Release All
        run: |
          version="$(./version/get_version.sh)"
          gh release create "$version" bin.tar.gz --title "$version" --generate-notes --repo https://github.com/warrenwoolseyiii/HLK-LD1125H-Driver --target ci
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
